# generated by wxGlade 1.1.0b1 on Thu Oct 17 18:24:16 2024
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx qw[:allclasses];
use strict;

# begin wxGlade: dependencies
use Wx::ArtProvider qw/:artid :clientid/;
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package ChordPro::Wx::MessagesPanel_wxg;

use Wx qw[:everything];
use base qw(Wx::Panel);
use strict;

# begin wxGlade: dependencies
use Wx::ArtProvider qw/:artid :clientid/;
# end wxGlade

sub new {
    my( $self, $parent, $id, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: ChordPro::Wx::MessagesPanel_wxg::new
    use ChordPro::Wx::Utils;
    $style = wxTAB_TRAVERSAL
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $pos, $size, $style, $name );
    
    $self->{sz_msg} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sz_msg}->Add($self->{sizer_2}, 0, wxEXPAND, 0);
    
    $self->{buttonMessage} = Wx::Button->new($self, wxID_ANY, "Hide Messages", wxDefaultPosition, wxDefaultSize, wxBORDER_NONE);
    $self->{buttonMessage}->SetMinSize(Wx::Size->new(150, -1));
    $self->{buttonMessage}->SetBitmap(Wx::Bitmap->new("/Users/Desbeers/Github/Clones/ChordPro/lib/ChordPro/res/icons/a-settings-outline.png", wxBITMAP_TYPE_ANY), wxTOP);
    $self->{buttonMessage}->SetBitmapPressed(Wx::Bitmap->new("/Users/Desbeers/Github/Clones/ChordPro/lib/ChordPro/res/icons/a-settings-outline-pressed.png", wxBITMAP_TYPE_ANY));
    $self->{sizer_2}->Add($self->{buttonMessage}, 0, wxALL, 6);
    
    my $static_line_1 = Wx::StaticLine->new($self, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLI_VERTICAL);
    $self->{sizer_2}->Add($static_line_1, 0, wxEXPAND, 0);
    
    $self->{sizer_2}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{bmb_clear} = Wx::BitmapButton->new($self, wxID_ANY, Wx::ArtProvider::GetBitmap(wxART_DELETE, wxART_TOOLBAR, wxDefaultSize));
    $self->{bmb_clear}->SetToolTip("Clear messages");
    $self->{bmb_clear}->SetSize($self->{bmb_clear}->GetBestSize());
    $self->{sizer_2}->Add($self->{bmb_clear}, 0, wxEXPAND|wxRIGHT, 4);
    
    $self->{bmb_save} = Wx::BitmapButton->new($self, wxID_ANY, Wx::ArtProvider::GetBitmap(wxART_FILE_SAVE_AS, wxART_TOOLBAR, wxDefaultSize));
    $self->{bmb_save}->SetToolTip("Save messages to file");
    $self->{bmb_save}->SetSize($self->{bmb_save}->GetBestSize());
    $self->{sizer_2}->Add($self->{bmb_save}, 0, wxEXPAND|wxRIGHT, 4);
    
    $self->{t_msg} = Wx::TextCtrl->new($self, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    $self->{sz_msg}->Add($self->{t_msg}, 1, wxEXPAND, 0);
    
    $self->{sizer_1} = Wx::FlexGridSizer->new(1, 4, 0, 5);
    $self->{sz_msg}->Add($self->{sizer_1}, 0, wxEXPAND|wxTOP, 5);
    
    $self->{l_status} = Wx::StaticText->new($self, wxID_ANY, "Status");
    $self->{l_status}->Show(0);
    $self->{sizer_1}->Add($self->{l_status}, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    
    $self->{button_3} = Wx::Button->new($self, wxID_CLEAR, "");
    $self->{button_3}->Show(0);
    $self->{sizer_1}->Add($self->{button_3}, 0, 0, 5);
    
    $self->{button_1} = Wx::Button->new($self, wxID_SAVE, "");
    $self->{button_1}->Show(0);
    $self->{sizer_1}->Add($self->{button_1}, 0, 0, 5);
    
    $self->{b_hide} = Wx::Button->new($self, wxID_ANY, "Hide Messages");
    $self->{b_hide}->Show(0);
    $self->{sizer_1}->Add($self->{b_hide}, 0, 0, 0);
    
    $self->{sizer_1}->AddGrowableCol(0);
    
    $self->SetSizer($self->{sz_msg});
    $self->{sz_msg}->Fit($self);
    
    $self->Layout();
    Wx::Event::EVT_BUTTON($self, $self->{buttonMessage}->GetId, $self->can('OnHide'));
    Wx::Event::EVT_BUTTON($self, $self->{bmb_clear}->GetId, $self->can('OnMsgClear'));
    Wx::Event::EVT_BUTTON($self, $self->{bmb_save}->GetId, $self->can('OnMsgSave'));
    Wx::Event::EVT_BUTTON($self, $self->{button_3}->GetId, $self->can('OnMsgClear'));
    Wx::Event::EVT_BUTTON($self, $self->{button_1}->GetId, $self->can('OnMsgSave'));
    Wx::Event::EVT_BUTTON($self, $self->{b_hide}->GetId, $self->can('OnHide'));

    # end wxGlade
    return $self;

}


sub OnHide {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::MessagesPanel_wxg::OnHide <event_handler>
    warn "Event handler (OnHide) not implemented";
    $event->Skip;
    # end wxGlade
}


sub OnMsgClear {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::MessagesPanel_wxg::OnMsgClear <event_handler>
    warn "Event handler (OnMsgClear) not implemented";
    $event->Skip;
    # end wxGlade
}


sub OnMsgSave {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::MessagesPanel_wxg::OnMsgSave <event_handler>
    warn "Event handler (OnMsgSave) not implemented";
    $event->Skip;
    # end wxGlade
}


# end of class ChordPro::Wx::MessagesPanel_wxg

1;

